# Generated by Django 3.0.6 on 2020-05-11 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('map_link', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=250)),
                ('start_date', models.DateField(default=datetime.date(2020, 5, 11))),
                ('end_date', models.DateField(default=datetime.date(2020, 5, 11))),
                ('planning_file', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField(default=datetime.date(2020, 5, 11))),
                ('end_date', models.DateField(default=datetime.date(2020, 5, 11))),
                ('number_beds', models.CharField(blank=True, max_length=2)),
                ('breakfast', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_not_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='trips.City')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('start_date', models.DateField(default=datetime.date(2020, 5, 11))),
                ('end_date', models.DateField(default=datetime.date(2020, 5, 11))),
                ('airline_name', models.CharField(blank=True, max_length=100)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='trips.Trip'),
        ),
    ]
