# Generated by Django 3.0.5 on 2020-04-17 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=250)),
                ('map_link', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 11, 40, 10, 693595))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 11, 40, 10, 693595))),
                ('planning_file', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 11, 40, 10, 697584))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 11, 40, 10, 697584))),
                ('number_beds', models.CharField(blank=True, max_length=2)),
                ('breakfast', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_not_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='trips.City')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 11, 40, 10, 694593))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 11, 40, 10, 694593))),
                ('airline_name', models.CharField(blank=True, max_length=100)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='trips.Trip'),
        ),
    ]
