# Generated by Django 3.0.5 on 2020-04-17 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name_city',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 12, 10, 40, 348289)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 12, 10, 40, 348289)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 12, 10, 40, 349286)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 12, 10, 40, 349286)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 12, 10, 40, 348289)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 12, 10, 40, 347297)),
        ),
    ]
