# Generated by Django 3.0.5 on 2020-04-17 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200417_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 14, 23, 363893)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 14, 23, 363893)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 14, 23, 364891)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 14, 23, 364891)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 14, 23, 362895)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 14, 23, 362895)),
        ),
    ]
