# Generated by Django 3.0.6 on 2020-05-17 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200512_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 17)),
        ),
    ]
