# Generated by Django 3.0.6 on 2020-05-18 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200517_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='trips.City')),
            ],
        ),
    ]
