# Generated by Django 3.0.5 on 2020-04-17 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200417_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 15, 25, 791634)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 15, 25, 791634)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 15, 25, 792631)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 15, 25, 792631)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 15, 25, 790637)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 14, 15, 25, 790637)),
        ),
    ]
