# Generated by Django 3.0.5 on 2020-04-17 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20200417_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 17)),
        ),
    ]
